const errorData = {
    100: { brief: "No Heap memory available", description: "No Heap memory available" },
    101: { brief: "Stack monitoring: stack consumption has reached error threshold.", description: "The stack consumption has reached error threshold. A safe operation is no longer possible. The additional info 1 of the error message shows the task number in which the stack consumption is too large." },
    102: { brief: "Error during indirect function access", description: "Error during indirect function access" },
    103: { brief: "Real time load critical", description: "The calculation time load of the real time is too high." },
    114: { brief: "Error division by zero", description: "Division by zero occurred in a floating point division." },
    115: { brief: "Invalid value for floating point operation", description: "An invalid floating point value (e.g. NaN: not a number) was detected in a floating point operation." },
    116: { brief: "Timeout of I2C Bus Read/Write Eeprom", description: "A timeout error occurred in the I2C Bus. The serial I2C EEPROM is connected to the DSP via the I2C Bus. The error may lead to an incorrect board configuration." },
    118: { brief: "Error while reading or writing the hardware board data", description: "An error has occurred while reading or writing the hardware board data." },
    119: { brief: "Drive no longer synchronous with fieldbus", description: "The error is enabled if the synchronization signal of the fieldbus is more than once out of the synchronous window after a successful synchronization." },
    121: { brief: "Measured RT fieldbus cycle too large", description: "The error is triggered when the fieldbus cycle that is measured in the FPGA is greater than the parameterized set value fieldbus cycle." },
    122: { brief: "Measured fieldbus cycle too small", description: "The fieldbus cycle that is measured in the FPGA is smaller than the parameterized set value fieldbus cycle" },
    123: { brief: "RT fieldbus jitter greater than the synchronizer window", description: "The error is triggered when the jitter of the fieldbus interrupt that is measured in the FPGA is greater than the parameterized synchronizer window." },
    124: { brief: "PWM Counter 1 not synchronous with the DSP time dial system", description: "The error is triggered when the PWM counter of Drive 1 is no longer synchronous with the time dial system of the DSP." },
    126: { brief: "RT fieldbus run time error", description: "The error is triggered when an error occurs in the chronological order of data transfer in the participating modules of the fieldbus system." },
    127: { brief: "Timeout fieldbus interrupt", description: "The error is triggered when more than 3 fieldbus interrupts have failed. The synchronization will be initiated again." },
    128: { brief: "Unknown identification System FPGA", description: "Identification of system FPGA is unknown in the DSP" },
    129: { brief: "System FPGA version does not fit to DSP software", description: "System FPGA version does not fit to DSP software" },
    130: { brief: "The fallback version was booted by Bootloader 1", description: "The fallback version was booted by Bootloader 1" },
    131: { brief: "The communication firmware has booted the fallback version", description: "The communication firmware has booted the fallback version" },
    132: { brief: "The firmware has booted the fallback version", description: "The firmware has booted the fallback version" },
    133: { brief: "The FPGA has booted the fallback version", description: "The FPGA has booted the fallback version" },
    134: { brief: "System FPGA and option module type are not compatible", description: "The system FPGA is incompatible with the connected option module. An error occurs during the booting procedure." },
    135: { brief: "Error while programming to flash", description: "Error while programming to flash" },
    137: { brief: "Time dial computation time overrun", description: "It is being monitored whether the time dials exceed the run time of MAX_ZS_TIME_LIMIT_IN_TICK = 60 µs too frequently." },
    138: { brief: "Cycle2 duration too long", description: "Cycle2 duration more than 1% too long in relation to one second. The CPU is overloaded, computation too great." },
    139: { brief: "Drive not synchronous with RT fieldbus (Warning)", description: "This warning message is issued when the synchronization of the drive with the fieldbus is activated (Parameter Z156.1–), but it has not yet occurred (Parameter Z156.2–)." },
    140: { brief: "General firmware error, e.g. switch", description: "General firmware error, e.g. switch" },
    141: { brief: "Operating system error", description: "Error in context with the operating system" },
    142: { brief: "Method not implemented", description: "Method not implemented" },
    144: { brief: "invalid file type", description: "invalid file type" },
    145: { brief: "File already open", description: "File already open" },
    146: { brief: "Maximum size of file reached (writing reading)", description: "Maximum size of file reached (writing reading)" },
    147: { brief: "File not opened", description: "File not opened" },
    148: { brief: "File not opened for this access (Read Write access)", description: "File not opened for this access (Read Write access)" },
    149: { brief: "Indicated ID wrong", description: "Indicated ID wrong" },
    150: { brief: "Indicated index does not exist (too large)", description: "Indicated index does not exist (too large)" },
    151: { brief: "Parameter element cannot be written", description: "Parameter element cannot be written" },
    152: { brief: "External access not permitted", description: "External access not permitted" },
    153: { brief: "Value less minimum value", description: "Value less minimum value" },
    154: { brief: "Value greater maximum value", description: "Value greater maximum value" },
    155: { brief: "Value error", description: "Value error" },
    156: { brief: "Value cannot be changed due to the operating condition", description: "Value cannot be changed due to the operating condition" },
    157: { brief: "wrong axis index", description: "wrong axis index" },
    158: { brief: "Format information wrong", description: "Format information wrong" },
    159: { brief: "Error while reading system data", description: "Error while reading system data" },
    168: { brief: "No write permission for the actual access level", description: "Parameter cannot be changed due to the access protection. No write permission for the actual access level." },
    169: { brief: "Application error for testing the error responses", description: "The error can be used to test the different error responses, e.g. pullback, without triggering a „true“ error." },
    170: { brief: "Firmware for communication processor could not be downloaded", description: "The error is messaged, if the firmware could not be downloaded to the communication processor at the boot sequence." },
    171: { brief: "Wrong power unit serial number", description: "The serial number of the power unit is unknown" },
    172: { brief: "Lead drive error", description: "Error within communication between two drives. The coupled drive reported an error." },
    173: { brief: "PLC Translation error", description: "Error when translating the PLC project" },
    174: { brief: "PLC runtime error", description: "PLC runtime error" },
    175: { brief: "Application error 1", description: "Freely definable application error 1" },
    176: { brief: "Application error 2", description: "Freely definable application error 2" },
    177: { brief: "Application error 3", description: "Freely definable application error 3" },
    178: { brief: "Application error 4", description: "Freely definable application error 4" },
    179: { brief: "Application error 5", description: "Freely definable application error 5" },
    181: { brief: "Value can be changed in inhibit state only", description: "The new parameter value is not accepted" },
    201: { brief: "Exceeded limit pos. speed error value", description: "Speed error value > Maximum positive speed error value" },
    202: { brief: "Exceeded limit neg. speed error value", description: "Speed error value < Maximum negative speed error value" },
    203: { brief: "Positive overspeed limit exceeded x2", description: "speed actual value > Positive overspeed limit" },
    204: { brief: "Negative overspeed limit exceeded x2", description: "speed actual value < Neg. overspeed limit" },
    205: { brief: "Motor i2t overload", description: "The current i2t value has exceeded the limit value for the i2t model." },
    206: { brief: "LT monitoring approached; max. torque current was limited", description: "I*t monitoring of power unit is operating; the maximum available torque current is limited." },
    207: { brief: "Exceeded position error limit 1", description: "Error occurs when position error limit 1 is exceeded." },
    208: { brief: "Exceeded position error limit 2", description: "The error occurs when position error limit 2 is exceeded" },
    209: { brief: "Blockage monitoring: Blocking time 1 exceeded", description: "The drive is blocked longer than the set Blockade Time Limit 1" },
    210: { brief: "Blockage monitoring: Blocking time 2 exceeded", description: "The drive is blocked longer than the set Blockade Time Limit 2" },
    211: { brief: "Error While Monitoring the Field Angle", description: "Error while monitoring the field angle is greater than 45°" },
    212: { brief: "Parameterization allows exceeding of the maximum speed of the motor", description: "The set value for the max. speed mech. can be exceeded because of the existing parameter settings." },
    213: { brief: "Position difference greater than threshold in gantry mode", description: "The difference of the position in gantry mode is greater than the variable threshold." },
    214: { brief: "Gantry mode: current difference greater than threshold", description: "In gantry mode the current difference is greater than the variable threshold" },
    215: { brief: "Controller fan not working", description: "The fan of the controller board is switched on but the controller gets no feedback from the tachometer." },
    216: { brief: "Power unit monitoring responded; PWM frequency reduced", description: "Power unit monitoring (temperature model) responded; PWM frequency reduced (halved)" },
    217: { brief: "Dual-Use: electrical frequency to high", description: "This device is a dual-use-device and the electrical frequency is to high. The maximum value is 600 Hz Output frequency." },
    218: { brief: "Peak current of power unit is reduced", description: "The power unit peak current is reduced to protect the unit from damage" },
    219: { brief: "Warning motor 12t overload", description: "Warning: motor i²t overload" },
    220: { brief: "Power unit overload during operation mode voltage setting", description: "Power unit overload. In the operation mode, voltage setting, the current cannot be limited." },
    221: { brief: "Exceedance warning threshold of real power", description: "Only für single Phase Units with DC link supply from mains. Here the real power has to be limited, otherwise the DC link will not get enough energy from mains." },
    222: { brief: "Exceedance error threshold of real power limitation", description: "Only for single Phase Units with DC link supply from mains. Here the real power has to be limited, otherwise the DC link will not get enough energy from mains." },
    223: { brief: "Fan failure", description: "One or several fans failed" },
    231: { brief: "Dual-use: electrical frequency too high", description: "The output frequency is limited to 600 Hz corresponding to the export restrictions. A dual-use device is necessary if higher frequencies are required." },
    400: { brief: "Amplitude of the encoder signal too small", description: "Encoder monitoring has detected an amplitude that is too small at Sin2+cos2 monitoring. Either the encoder has a problem or the monitoring threshold is set too great." },
    401: { brief: "Amplitude of the encoder signal too great", description: "Encoder monitoring has detected an amplitude that is too great at Sin2+cos2." },
    402: { brief: "Error while initializing the position through Sin/Cos signals.", description: "Error while initializing the position (the analogous signals do not agree with the position which was digital read out)." },
    403: { brief: "Encoder monitoring: Overspeed due to sector error", description: "Sector error occurred while the encoder evaluation, which means the calculated speed is too great" },
    404: { brief: "Signal monitoring at square-wave incremental encoder", description: "The signal monitoring of a square-wave incremental encoder has recognized an error." },
    405: { brief: "CRC error in received data", description: "CRC error in received data from EnDat 2.1, HIPERFACE DSL or SSI" },
    406: { brief: "Lighting failure EnDat interface", description: "The error is triggered by module EnDat interface when the absolute encoder reports a lighting failure via the EnDat interface. Without lighting, the optical sampling system of the encoder no longer works and no valid position information can be calculated anymore." },
    407: { brief: "Signal amplitude too small EnDat interface", description: "The error is triggered by the module EnDat interface when the absolute encoder reports via the EnDat interface that the amplitude of the Sine/Cosine signals is too small. Sine/Cosine signals that are too small can lead to a position loss." },
    408: { brief: "Position error EnDat interface", description: "The error is triggered by the module EnDat interface when an error occurred during the calculation of the absolute position in the absolute encoder. An incorrect absolute position can lead to miscommunication for synchronous motors." },
    409: { brief: "Overvoltage EnDat interface", description: "The error is triggered by the module EnDat interface when the absolute absolute encoder reports via the EnDat interface that the supply voltage applied to the encoder is too high." },
    410: { brief: "Undervoltage EnDat interface", description: "The error is triggered by the module EnDat interface when the absolute encoder reports via the EnDat interface that the supply voltage is too low." },
    411: { brief: "Overcurrent EnDat interface", description: "The error is triggered by the module EnDat interface when the absolute encoder reports via the EnDat interface that the encoder supply current is too high." },
    412: { brief: "Battery error EnDat interface", description: "The error is triggered by the module EnDat interface when the Multiturn absolute encoder reports via the EnDat interface that the supply battery must be replaced. The battery voltage provides position information for the Multiturn encoder in the memory when the controller is switched off and no supply voltage is provided for the encoder." },
    413: { brief: "Alarm Bit set EnDat interface has set alarm Bit (collective message).", description: "Alarm Bit set EnDat interface has set alarm Bit (collective message)." },
    414: { brief: "Error during reception: Address mirroring returns an error", description: "Error during reception: Address mirroring returns an error" },
    415: { brief: "Variance of encoder signals exceeds adjustable limit", description: "The variance of encoder signals exceeds adjustable limit" },
    416: { brief: "Touch probe: trigger zero pulse without incremental encoder", description: "The touch probe measurement is configured to trigger by a zero pulse, but the used encoder does not provide a zero pulse." },
    417: { brief: "Warning Collision of frequency EnDat encoder", description: "EnDat encoder has messaged warning collision of frequency, see Z137.38; preventative maintenance is recommended." },
    418: { brief: "Warning Excess temperature EnDat encoder", description: "EnDat encoder has messaged warning excess temperature; see Z137.38 and error number 407; preventative maintenance is recommended." },
    419: { brief: "Warning Lighting controller reserve reached", description: "EnDat encoder has messaged warning „Lighting controller reserve reached“; see Z137.38 and error number 406; preventative maintenance is recommended in order to avoid lighting failure." },
    420: { brief: "Warning Battery load to small", description: "EnDat encoder has messaged warning „Battery load to small“; see Z137.38 and error number 412; preventative battery change is recommended." },
    421: { brief: "Warning Reference point", description: "EnDat encoder has messaged warning Reference point; see Z137.38; preventative maintenance is recommended." },
    422: { brief: "Parity errors in received data", description: "Parity errors in the received data of SSI" },
    423: { brief: "Received data invalid", description: "Received data of SSI encoder are invalid." },
    424: { brief: "Encoder emulation: Error configuration", description: "Configuration error, further details in status Z172.2 or Z172.11" },
    425: { brief: "Encoder emulation: Run time error", description: "Run time error, further details in status Z172.2 or Z172.11" },
    426: { brief: "SSI encoder emulation: Error configuration", description: "Error in configuration of SSI encoder emulation, for details see status Z173.2" },
    427: { brief: "SSI encoder emulation: run-time error", description: "Run-time error, for details see status Z173.2" },
    428: { brief: "Encoder monitoring: difference between analog and digital position too high", description: "HIPERFACE encoders: The absolute position is read via the serial HIPERFACE interface and compared to the analog position calculated from the analog SinCos signals by the FPGA. If the position errors absolute value is higher than the defined error threshold this error is set." },
    429: { brief: "EnDat baud rate too low for digital position transmission", description: "If the calculation and transmission of the digital position of the EnDat encoder lasts longer than 61.5 µs the error is displayed." },
    430: { brief: "Invalid encoder type", description: "The set encoder type is not permitted because it is not supported by the installed FPGA." },
    431: { brief: "Transmitting error between the DSL master/slave", description: "Failure in the HIPERFACE DSL encoder due to the EMC or shock/vibration. Position is estimated as long as the error is applied." },
    500: { brief: "New set value not transferred to the controller soon enough", description: "The new set value was not transferred to the controller through the set value manager for a minimum of three times soon enough." },
    501: { brief: "Current controller cycle time > RT0-Cycle time", description: "The time slice RT0 includes the speed and position controller, the encoder evaluation and the motor control. The current controller cycle time is defined by the setting of the PWM frequency." },
    503: { brief: "Torque coupling improper drive operating mode", description: "Operating mode must be Speed control or Speed setting. In the other operating modes the error will be initiated, if it will be tried to activate the torque coupling" },
    504: { brief: "Torque coupling configuration error", description: "Configuration error: Device internal cross communication at Mono unit / single axis unit impossible" },
    505: { brief: "Fieldbus cycle time < RT0-Cycle time", description: "The cycle time of the fieldbus task is set via the fieldbus cycle time. The RT0-Cycle time is set in Z1.8." },
    600: { brief: "Terminal position search Inject. Plausib. Step 1", description: "In step 1 the injection procedure runs successively twice or the pole position is determined twice. If both results show a major difference (or about 30°), this bit is set." },
    601: { brief: "Terminal position search Inject. Plausib. Step 2", description: "In step 2 the carrier current is too low, in order to create the required saturation so that the content of the 2nd harmonic I2 does not reach the level which is indicated in parameter Z133.10." },
    602: { brief: "Overcurrent with notch position search Method 2", description: "Overcurrent with notch position search Method 2 (using injection)" },
    702: { brief: "Rotor position at synchronous machine is unknown", description: "The rotor position of the synchronous drive is unknown. Either the rotor position offset or the absolute position could not be read from the encoder or the synchronous drive is used with a incremental encoder and a rotor position identification has not been executed yet." },
    703: { brief: "Error writing rotor position offset to encoder", description: "An error occurred while writing the rotor position offset into the encoder" },
    704: { brief: "For synchronous machine: encoder transmission not permitted", description: "No encoder transmission was supported for synchronous machine. A transmission factor not equal to 1:1 was read from the motor type plate." },
    705: { brief: "Motor temperature for characteristic curve of ASM slip invalid, lower than -50°C or higher than 200°C", description: "The motor temperature that is measured via the KTY encoder is monitored for asynchronous motors due to slip characteristic curves If the temperature is lower than -50°C or higher than 200°C, the temperature values are assumed to be invalid and the error will be triggered." },
    709: { brief: "Motor excess temperature", description: "The measured temperature is higher than permitted" },
    710: { brief: "Motor Temperature Threshold1 exceeded", description: "Motor temperature warning threshold 1 exceeded" },
    711: { brief: "Motor Temperature Threshold 2 exceeded", description: "Motor temperature warning threshold 2 exceeded" },
    712: { brief: "Short circuit on temperature sensor", description: "Short circuit on temperature encoder" },
    713: { brief: "Temperature sensor is not connected", description: "Temperature encoder is not connected" },
    714: { brief: "Motor excess temperature PTC resistor", description: "Motor excess temperature recognized by temperature switch" },
    716: { brief: "Notch position not found", description: "An error occurred while identifying the rotor position of the synchronous machine. The rotor position has not been identified." },
    717: { brief: "Excess voltage occurred during resistance measurement", description: "Error during identification of motor parameters. The maximum permitted phase voltage was exceeded during the resistance measurement." },
    718: { brief: "Voltage limit accessed during resistance measurement", description: "Error during identification of motor parameters. The voltage limit was reached during the resistance measurement." },
    719: { brief: "Timeout during motor identification", description: "Error during identification of motor parameters. The maximum permitted phase voltage was exceeded during the resistance measurement." },
    720: { brief: "An encoder is not activated", description: "An encoder is required for this operating mode" },
    721: { brief: "Special case Kt = 0", description: "Special case Kt = 0, no correct operation possible, isq set value is forced to 0." },
    800: { brief: "Special function already used for another digital input", description: "Special function such as hardware limit switch 1 was already used for another digital input" },
    801: { brief: "Digital output already used", description: "This digital output is already used by another special function or by another assignment." },
    802: { brief: "OM power steering pump current > 22mA", description: "Power steering pump I/O module error overcurrent. Level 22 mA." },
    803: { brief: "OM power steering pump current < 3.6 mA", description: "OM power steering pump undercurrent. Level 3.6 mA." },
    804: { brief: "OM power steering pump analog input not placed", description: "Power steering pump I/O: analog input cannot be activated because not placed" },
    805: { brief: "OM power steering pump analog output not placed", description: "Power steering pump can not be activated because it is not placed." },
    806: { brief: "OM power steering pump error configuration", description: "The system FPGA is not compatible with the power steering pump I/O module" },
    900: { brief: "Reference run required and not carried out", description: "The start of the active operating mode requires a one-time reference run (homing) after activating the controller." },
    901: { brief: "Problem during homing", description: "A homing error has occurred. Possible error causes: An invalid homing mode was selected." },
    902: { brief: "Monitoring the block for positive direction", description: "Monitoring has detected a positioning attempt in positive direction" },
    903: { brief: "Monitoring the block for negative direction", description: "Block for negative direction has detected a positioning attempt in negative direction." },
    904: { brief: "Positioning time monitoring reports Timeout", description: "Monitoring will become active as soon as the position set value is equal to the target position at the end of positioning." },
    905: { brief: "Error limit switch monitoring", description: "This error occurs under the following conditions: Both hardware limit switches set simultaneously." },
    906: { brief: "Negative hardware limit switch overrun", description: "Negative hardware limit switch overrun" },
    907: { brief: "Positive hardware limit switch overrun", description: "Positive hardware limit switch overrun" },
    908: { brief: "Negative software limit switch overrun", description: "Target position to be approached is smaller than the negative software limit switch." },
    909: { brief: "Positive software limit switch overrun", description: "Target position to be approached is greater than the positive software limit switch." },
    910: { brief: "Overspeed detected at set value input", description: "Overspeed detected at set value input: In the operating mode speed control or speed setting a set value was written exceeding the maximum interpolating speed set value of the set value manager." },
    911: { brief: "New set value missing for Set-of-set values", description: "The next set value did not arrive soon enough at the drive controller during the positioning process Set Value Specification (Set of set values)." },
    912: { brief: "Target position >= Modulo value", description: "If in the target position a value is entered which is greater or equal than the modulo value, this error will be output at start of the positioning." },
    913: { brief: "Monitoring of positive stop generates an error message", description: "The error will be set, when the positive stop was detected and the position actual value is outside of the symmetrical monitoring window or the standstill message is not active anymore." },
    914: { brief: "Positive stop drive impossible", description: "Positive stop drive impossible is generated in case of the actual operation state. Others reasons are an active master-slave torque coupling or an active gantry-function." },
    915: { brief: "Abort of the command at positive stop", description: "If the command 'positive stop drive' is aborted while the positive stop is not detected by the drive but the standstill message is set and the clamping torque is reached, this error will be generated." },
    916: { brief: "Encoder of master axis is switched off", description: "If the synchronous operation mode in the 'Real master axis' mode is activated an inactive encoder of master axis was recognized." },
    917: { brief: "Operating mode position control not initialized", description: "The operating mode position control could not be initialized correctly." },
    1000: { brief: "Power unit has canceled the controller activation", description: "Error is triggered in the module Operating Type Manager when a power unit error has occurred." },
    1001: { brief: "Bridge short circuit", description: "The error is triggered when the IGBT switch sequence monitoring of the pulse width modulation does not detect a permitted status." },
    1002: { brief: "Power unit maximum DC link voltage exceeded", description: "The actual value of the DC link voltage is displayed through Parameter 130.03. When a limit that is defined by the power unit is exceeded, the power unit will switch off with error." },
    1003: { brief: "Overcurrent error in the power unit", description: "The limit of the maximum current of the power unit is exceeded in one of the three phases." },
    1004: { brief: "Power section fault current / earth fault monitoring", description: "The ground fault current of the power unit is monitored to recognize a motor fault current." },
    1005: { brief: "In supply mode is 0x8001 event though DC link voltage is greater than 90 V (mains), Danger Load Resistor Damage", description: "Though DC link voltage is greater than 90 V in Supply mode is set 0x8001. There is a danger of overloading of the load resistor." },
    1006: { brief: "Power unit excess temperature", description: "If the power unit exceeds a power unit dependent cut-off temperature, the power unit will be blocked." },
    1007: { brief: "Power unit safety relay", description: "The error is triggered when the voltage supply of the transistor activation in the power unit is switched off through the safety relay with activated control activation." },
    1010: { brief: "Bit bar power unit cannot be read", description: "When multiple errors occur on the converter and power unit, the evaluation of the bit bar of the power unit interface will display the differentiation of the errors." },
    1011: { brief: "Incompatibility between characteristic data OWE and LT (Mono unit)", description: "Incompatibility between the stored characteristic data OneWireEEPROM and Power unit (Mono unit)" },
    1012: { brief: "Error while reading out characteristic data via HIPERFACE from LT", description: "Error while reading out characteristic data via HIPERFACE from power unit (with Mono units)" },
    1013: { brief: "Deactivation through safety technology", description: "The drive function is disabled by the safety technology (Safe Torque Off)" },
    1014: { brief: "DSP Timeout error because the DSP has not updated the Pot ABC Registers", description: "DSP Timeout error because the DSP has not updated the Pot ABC Registers" },
    1015: { brief: "Phase error timeout", description: "Phase error timeout" },
    1016: { brief: "Mains failure (Mono unit)", description: "Message only at Mono unit (device with separate supply)" },
    1017: { brief: "Mains undervoltage", description: "Mains undervoltage" },
    1018: { brief: "Mains overvoltage", description: "Mains overvoltage" },
    1019: { brief: "Undervoltage DC link voltage", description: "Undervoltage DC link voltage is detected through the FPGA." },
    1020: { brief: "Heat sink excess temperature", description: "Switch off due to exceeding of the maximum heat sink temperature" },
    1021: { brief: "Excess temperature inside temperature", description: "Switch off due to exceeding of the maximum heat sink temperature" },
    1022: { brief: "Cable break heat sink temperature encoder", description: "Cable break heat sink temperature encoder" },
    1023: { brief: "Communication error with MUX register to the FPGA", description: "Communication error with Multiplex Register interface to the FPGA" },
    1024: { brief: "Current offset error", description: "The error will be triggered when the measured current offset is greater than 5% of the possible measuring range of the AD converter." },
    1025: { brief: "Setting of pulse enable (IF) and PWM not synchronous with DSP", description: "The error is triggered when the PWM counter is no longer synchronous with the DSP Interrupt system and the pulse activation has been enabled." },
    1032: { brief: "Error DC-link supply", description: "DC-link undervoltage detected or signal 'supply ready for use' of the Signal Bus is low." },
    1033: { brief: "Signal bus line warning active", description: "Signal bus line 'Warning' is active" },
    1034: { brief: "Signal bus line error", description: "Signal bus line Error is active" },
    1035: { brief: "No valid Lt data available in the One Wire Eeprom", description: "Warning: No valid Lt data available in the One Wire EEPROM." },
    1036: { brief: "Error occurred while writing the Lt data to the One Wire Eeprom", description: "Error occurred while writing the Lt data to the One Wire EEPROM" },
    1037: { brief: "Signal error during communication with the One Wire EEprom", description: "Signal error during communication with the One Wire EEPROM" },
    1038: { brief: "No Lt One Wire EEProm", description: "Warning: No Lt Data One Wire EEPROM exists!" },
    1039: { brief: "reserved", description: "reserved" },
    1040: { brief: "reserved", description: "reserved" },
    1041: { brief: "reserved", description: "reserved" },
    1042: { brief: "reserved", description: "reserved" },
    1043: { brief: "Warning: Undervoltage DC link voltage", description: "Warning: Undervoltage DC link voltage" },
    1044: { brief: "Warning: Undervoltage Mains", description: "Warning: Undervoltage Mains" },
    1045: { brief: "Warning: Overvoltage Mains", description: "Warning: Overvoltage Mains" },
    1046: { brief: "Warning: Deactivation through safety technology", description: "The safety function Safe Torque Off is active" },
    1047: { brief: "Warning: Phase failure", description: "This warning is set if a phase failure is recognized." },
    1048: { brief: "Warning: Mains failure / Supply not ready", description: "A mains failure was detected or the supply is not ready-to-operate." },
    1049: { brief: "Temperature warning threshold heat sink exceeded", description: "Temperature warning threshold heat sink exceeded" },
    1050: { brief: "Temperature warning threshold Inside Air exceeded", description: "Temperature warning threshold Inside Air exceeded" },
    1054: { brief: "DSP Timeout Error: DSP does not write the PWM Pot Registers in time, 3 times within 100 ms", description: "DSP Timeout Error: DSP does not write the PWM Pot Registers in time, 3 times within 100 ms" },
    1056: { brief: "Performance element 24 V Fail", description: "When the 24V supply voltage drops below a specific threshold the FPGA will activate a corresponding error bit in its status and block the pulses." },
    1057: { brief: "15 V fault - power cycle required", description: "The 15 V power supply failed." },
    1066: { brief: "SS1 stop forced by SAF module", description: "If SS1 function is activated on SAF-002/-003 module and an appropriate error occurs, the SAF module forces the SS1 stop function on the controller." },
    1070: { brief: "Change of the PWM frequency not possible. PWM frequency change is in progress.", description: "The new set PWM frequency is not accepted. The error can be caused: The previous PWM frequency change is in progress." },
    1071: { brief: "Timeout quick discharge", description: "Error at discharging the DC link" },
    1100: { brief: "Drive manager general error pulse enable", description: "When a pulse block has no reason that can be recognized by the drive manager (AM), there is a threat of an endless change of statuses in the AM." },
    1101: { brief: "Motor parking brake does not open when the drive ist started", description: "The motor parking brake should open in Automatic mode of the brake activation when the drive is activated but it does not." },
    1102: { brief: "Motor parking brake does not close when the drive is switched off", description: "The motor parking brake should close in Automatic mode of the brake activation when switching off after active braking, but it does not." },
    1103: { brief: "Cyclical monitoring of brake activation reports error", description: "The cyclical monitoring of the brake activation determines that the set value and actual status of the motor parking brake do not match." },
    1104: { brief: "Motor parking brake: Brake moment prior to opening the brake not reached", description: "The drive should build up in the Automatic mode of the brake activation during enable before opening the motor parking brake but cannot reach a stop moment." },
    1105: { brief: "Cyclical monitoring of the brake pad reports the error", description: "The cyclical monitoring of the brake pad detects a error." },
    1106: { brief: "Drive operation mode not allowed with this motor operation mode", description: "Drive operation mode not allowed with this motor mode operation mode. error caused when changing from state 3 to 4." },
    1107: { brief: "To this operation mode cannot be changed in operation mode 4", description: "To this operation mode cannot be changed in operation mode 4. No online change possible e.g. from speed control to find notch position." },
    1300: { brief: "Memory organization is faulty.", description: "Memory organization is faulty." },
    1301: { brief: "Invalid trigger configuration (both edges)", description: "Invalid trigger configuration in the ring buffer. Triggering to both edges is not possible." },
    1302: { brief: "no Trigger ID entered", description: "no Trigger ID entered" },
    1303: { brief: "no ID to read out data", description: "no ID to read out data" },
    1304: { brief: "no permission to read out data", description: "no permission to read out data" },
    1305: { brief: "No record for channel and axis", description: "No record for channel and axis" },
    1400: { brief: "Error while loading or saving the data record", description: "Error while loading or saving the data record" },
    1401: { brief: "No valid parameter file found", description: "No valid parameter file found" },
    1402: { brief: "CRC in parameter file not correct", description: "CRC in parameter file not correct" },
    1403: { brief: "Invalid data record number indicated for DSV command", description: "An invalid data record number was indicated for a data record command." },
    1500: { brief: "uBlaze Software has a critical error", description: "It was an critical error and uBlaze Software is no longer functional" },
    1501: { brief: "If there is no response from the slave (HPI-Buffer Initialization)", description: "Slave did not respond within specified time." },
    1502: { brief: "Message length is greater than HPI Buffer", description: "Message length is greater than HPI Buffer" },
    1503: { brief: "Access to HPI wrong channel", description: "Access to the wrong (non-existent) HPI-Channel" },
    1504: { brief: "HPI Channel was not initialized", description: "First Access to the HPI-channel was early as the initialization." },
    1505: { brief: "HPI buffer is empty", description: "HPI buffer has no user data available." },
    1506: { brief: "HPI buffer is full", description: "HPI buffer has user data available or old telegram data are not called for yet." },
    1507: { brief: "TCP IP Stack could not be initialized", description: "An error has occurred at initialization of TCP/IP stack" },
    1508: { brief: "SoE firmware error message", description: "SoE firmware sends an error message to the drive controller." },
    1509: { brief: "EtherCAT IP core cannot init EEPROM", description: "EtherCAT IP core cannot init EEPROM" },
    1510: { brief: "Sub device index invalid", description: "Sub device index invalid, i.e. out of range" },
    1511: { brief: "Firmware error fieldbus controller", description: "Fieldbus controller signaled a firmware error." },
    1512: { brief: "Faulty backup of operation data", description: "Faulty backup of operation data" },
    1513: { brief: "Illegal drive address", description: "A invalid drive address is set." },
    1514: { brief: "Error caused by memory allocation", description: "Error caused by memory allocation" },
    1515: { brief: "Faulty task start", description: "Operating system was not able to start a task." },
    1516: { brief: "Faulty init of scaling data", description: "Faulty init of scaling data" },
    1517: { brief: "Error during reading of the cyclic actual values", description: "Error during reading of the cyclic actual values" },
    1518: { brief: "Error during writing of the cyclic set values", description: "Error during writing of the cyclic set values" },
    1519: { brief: "Critical GDP error while initialization", description: "Incorrect reading or writing of important data via GPD. GPD means the communication between controller and fieldbus controller." },
    1520: { brief: "Invalid version of the controller firmware", description: "Installed controller firmware cannot be used with this type of fieldbus." },
    1521: { brief: "Warning: Error while reading service data", description: "Warning: Error while reading service data" },
    1522: { brief: "Warning: Error while writing service data", description: "Warning: Error while writing service data" },
    1523: { brief: "Error during command execution", description: "An error occurred during a command execution." },
    1524: { brief: "Timeout during command execution", description: "A timeout occurred during a command execution." },
    1525: { brief: "MST-Error; drive controller lost synchronization", description: "Sercos: MST incorrect SoE: controller signaled lost synchronization" },
    1526: { brief: "Error: MDT miss twice; watchdog timeout process data", description: "Sercos: failure of MDT SoE: watchdog timeout at process data" },
    1527: { brief: "Error during switch up of phase", description: "Error during switch up of the bus state" },
    1528: { brief: "Error during switch down of phase", description: "Error during switch down of the bus state" },
    1529: { brief: "Phase transition without ready acknowledge", description: "Sercos: switch up to CP3 not possible back to CP0. SoE: switch up to Safe-Op not possible back to Pre-OP." },
    1530: { brief: "Error: Invalid phase", description: "Invalid phase set." },
    1531: { brief: "Switch to non-initialized operation mode", description: "Switch to a not supported or unknown operation mode." },
    1532: { brief: "Error: Two drives with same address in ring", description: "Error message only possible using Sercos." },
    1533: { brief: "Error while reading sync data of drive controller", description: "Error when adjusting the synchronization data with the settings in the drive controller." },
    1534: { brief: "Overflow mailbox service", description: "Overflow during a fragmented mailbox service." },
    1535: { brief: "Invalid mailbox size", description: "Error detected when checking the mailbox size." },
    1536: { brief: "to 1555: see Application Manual SoE slave for BM2500/3000", description: "to 1555: see Application Manual SoE slave for BM2500/3000" },
    1556: { brief: "Error-Command; invalid sector", description: "A fieldbus controller command tried to access a not accessible sector of the application." },
    1557: { brief: "Initialization of PDC's failed", description: "Initialization of PDC's failed" },
    1558: { brief: "Invalid transition of operation mode", description: "Invalid transition of operation mode" },
    1559: { brief: "Invalid hardware-ID", description: "Invalid hardware-ID" },
    1560: { brief: "FPGA-version doesn't fit", description: "FPGA-version doesn't fit" },
    1561: { brief: "Invalid MDW during slave transmission", description: "Sercos: Invalid MDW during slave transmission" },
    1562: { brief: "to 1600: see Application Manual SoE slave for BM2500/3000", description: "to 1600: see Application Manual SoE slave for BM2500/3000" },
    1601: { brief: "SAFETY-FPGA-vs.-safety-lib.", description: "Invalid SAFETY FPGA-version or safety-lib. version." },
    1602: { brief: "Faulty update of safety parameter", description: "Error during parameter update in safety FPGA." },
    1603: { brief: "Critical FP protection test fault", description: "Critical error when running the FIELDPROGRAMM (FP)." },
    1604: { brief: "to 1700: see Application Manual SoE slave for BM2500/3000", description: "to 1700: see Application Manual SoE slave for BM2500/3000" }
};

function findError() {
    const input = document.getElementById("errorInput").value;
    const resultDiv = document.getElementById("result");
    resultDiv.innerHTML = "";

    if (input in errorData) {
        const error = errorData[input];
        resultDiv.innerHTML = `<h2>Error No: ${input}</h2>
                               <p><strong>Brief error text:</strong> ${error.brief}</p>
                               <p><strong>Error description:</strong> ${error.description}</p>`;
    } else {
        resultDiv.innerHTML = "<p>Error number not found.</p>";
    }
}
